# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AllCli < Formula
  desc "Inspect and manage common CLI tool contexts"
  homepage "https://github.com/oldwinter/all-cli"
  version "0.0.0-15.1.714830c"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oldwinter/all-cli/releases/download/v0.0.0-15.1.714830c/all-cli_0.0.0-15.1.714830c_darwin_amd64.tar.gz"
      sha256 "30b9ace3d434544f2c69ec5d52950ef5f5ca7483aa633dd3800202443ae75feb"

      define_method(:install) do
        bin.install "all-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oldwinter/all-cli/releases/download/v0.0.0-15.1.714830c/all-cli_0.0.0-15.1.714830c_darwin_arm64.tar.gz"
      sha256 "31cc14a8f7d69d3f8bf75fa37a4fe1c4fbf5767dcf3df07514d467b26ff39875"

      define_method(:install) do
        bin.install "all-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oldwinter/all-cli/releases/download/v0.0.0-15.1.714830c/all-cli_0.0.0-15.1.714830c_linux_amd64.tar.gz"
      sha256 "4a3652925e583aecef49c6219f681f7d1b5e559c433ada12e909ca52c9e71b74"
      define_method(:install) do
        bin.install "all-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oldwinter/all-cli/releases/download/v0.0.0-15.1.714830c/all-cli_0.0.0-15.1.714830c_linux_arm64.tar.gz"
      sha256 "8b93d5c9b67c5a70750129956a5ac0b0d98cfff9209327e52b57e1d9485409b6"
      define_method(:install) do
        bin.install "all-cli"
      end
    end
  end

  test do
    system "#{bin}/all-cli", "version"
  end
end
