# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AllCli < Formula
  desc "Inspect and manage common CLI tool contexts"
  homepage "https://github.com/oldwinter/all-cli"
  version "0.0.0-37.1.e1573cd"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oldwinter/all-cli/releases/download/v0.0.0-37.1.e1573cd/all-cli_0.0.0-37.1.e1573cd_darwin_amd64.tar.gz"
      sha256 "7a31a2892107adcd62c6d688572625a23a10e8432f6fe8144116d3a0d6725ee9"

      define_method(:install) do
        bin.install "all-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oldwinter/all-cli/releases/download/v0.0.0-37.1.e1573cd/all-cli_0.0.0-37.1.e1573cd_darwin_arm64.tar.gz"
      sha256 "91e6011a853e4419e76a6dfc94f46e21de9bfb9f38f0268b8cbe0d5d5500a5be"

      define_method(:install) do
        bin.install "all-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oldwinter/all-cli/releases/download/v0.0.0-37.1.e1573cd/all-cli_0.0.0-37.1.e1573cd_linux_amd64.tar.gz"
      sha256 "b9ad6a1d8976c1f8e9e0159cbbbd086ba125d5834d175b8dc90c7c34ca82fb37"
      define_method(:install) do
        bin.install "all-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oldwinter/all-cli/releases/download/v0.0.0-37.1.e1573cd/all-cli_0.0.0-37.1.e1573cd_linux_arm64.tar.gz"
      sha256 "1ef9997097c2a4b4886125c4217d254da202da316a2efd5e8137943c21c9a3fd"
      define_method(:install) do
        bin.install "all-cli"
      end
    end
  end

  test do
    system "#{bin}/all-cli", "version"
  end
end
